### ISSUE TITLE
notestockからのDeleteが処理できない

### ISSUE THREAD

**Issue by mei23** [mei23/misskey#2887]
## 💡 Summary
```
"activity":{
   "@context":"https://www.w3.org/ns/activitystreams",
   "id":"https://notestock.osa-p.net/users/voteguide/statuses/1628160012563617#delete",
   "type":"Delete",
   "actor":"https://notestock.osa-p.net/users/voteguide",
   "to":[
      "https://www.w3.org/ns/activitystreams#Public"
   ],
   "object":{
      "id":"https://notestock.osa-p.net/users/voteguide/statuses/1628160012563617"
   }
}
```
Objectにはtypeが必要かも
https://www.w3.org/TR/activitypub/#obj-id

いや、そもそも対象はAnnounceみたいなので
正しくは`Undo.Announce`？

```
activity:
  id: ...
  type: Undo
  object:
    id: https://notestock.osa-p.net/users/voteguide/statuses/1628160012563617
    type: Announce
    object: ...
```

## 📝 Steps to Reproduce

1.
2.
3.
