### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by mei23** [mei23/misskey#58]
# Summary

# Environment

**Comment by mei23** [comment]
- URLにポートが必要と誤解する→実際はhttps && 443なので不要
- 123で別のポート採番が必要と誤解する→実際は間違いなく443
- 456が特権ポートなのでサンプルとしてよくない
- urlとportの既定値もよくなさげ
```
# URL and Port settings overview
# e.g., If you want to realize following structure:
#
#               +--- https://example.com:123 ----------+
# +------+      |+-------------+      +---------------+|
# | User | ---> || Proxy (123) | ---> | Misskey (456) ||
# +------+      |+-------------+      +---------------+|
#               +--------------------------------------+
#
# You need to set 'https://example.com:123' to 'url' prop and
# You need to set 456 to 'port' prop.
#
# In other words, the 'url' prop should be the final accessible URL seen by a user.
# 'port' prop is a port that the Misskey server should actually listen
# on and it is not necessarily the port that a user accesses.

url: http://localhost/

# A port that your Misskey server should listen.
# This value is not a port to use when accessing with a browser.
port: 80
```

**Comment by mei23** [comment]
こっちのほうがよりわかりやすそう  
ただし、Proxy必須となるのでProxyの手順も書かないといけない
```
# URL and Port settings overview
# e.g., If you want to realize following structure:
#
#               +----- https://example.com/ ------------+
# +------+      |+-------------+      +----------------+|
# | User | ---> || Proxy (443) | ---> | Misskey (3000) ||
# +------+      |+-------------+      +----------------+|
#               +---------------------------------------+
#
# You need to set 'https://example.com/' to 'url' prop and
# You need to set 3000 to 'port' prop.
#
# In other words, the 'url' prop should be the final accessible URL seen by a user.
# 'port' prop is a port that the Misskey server should actually listen
# on and it is not necessarily the port that a user accesses.

url: https://example.com/

# A port that your Misskey server should listen.
# This value is not a port to use when accessing with a browser.
port: 3000
```

**Comment by mei23** [comment]
# URL and Port settings overview
# e.g., If you want to realize following structure:
#
#               +- https://example.com/ -+
# +------+      |   +---------------+    |
# | User | ---> |   | Misskey (443) |    |
# +------+      |   +---------------+    |
#               +------------------------+
#
# You need to set 'https://example.com/' to 'url' prop and
# You need to set 443 to 'port' prop.
# You need to set Certificate in 'https' section.
# You need run Misskey as root.

url: https://example.com/

# A port that your Misskey server should listen.
# This value is not a port to use when accessing with a browser.
port: 443

https:

**Comment by mei23** [comment]
```
### 1. Misskey with Reverse Proxy deployment ###################
#
#               +----- https://example.com/ ------------+
# +------+      |+-------------+      +----------------+|
# | User | ---> || Proxy (443) | ---> | Misskey (3000) ||
# +------+      |+-------------+      +----------------+|
#               +---------------------------------------+
#
# You need setup reverse proxy. (eg. Nginx)
# You need comment out 'https' section.
#
url: https://example.com/

# A port that your Misskey server should listen.
# This value is not a port to use when accessing with a browser.
port: 3000


### 2. Misskey only deployment ###################
#
#               +- https://example.com/ -+
# +------+      |   +---------------+    |
# | User | ---> |   | Misskey (443) |    |
# +------+      |   +---------------+    |
#               +------------------------+
#
# You need to setup reverse proxy. (eg. Nginx)
# You need to run Misskey as root.
# You need to set Certificate in 'https' section.

url: https://example.com/

# A port that your Misskey server should listen.
# This value is not a port to use when accessing with a browser.
port: 443

https:
  key: /etc/letsencrypt/live/example.com/privkey.pem
  cert: /etc/letsencrypt/live/example.com/fullchain.pem
```
